#goreleaser from fscan project https://github.com/shadow1ng/fscan
name: Build and Release

on:
  release:
    types:
      - created
permissions:
 contents: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: git fetch --force --tags
        - uses: actions/setup-go@v3
          with:
            go-version: '1.20.x'
            cache: true
        # More assembly might be required: Docker logins, GPG, etc. It all depends
        # on your needs.
        - run: go install mvdan.cc/garble@latest
        - uses: goreleaser/goreleaser-action@v2
          with:
            # either 'goreleaser' (default) or 'goreleaser-pro':
            distribution: goreleaser
            version: latest
            args: -f .github/conf/.goreleaser.yml
            workdir: .
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}